# Common properties for all environments

# Set default profile to dev
spring.profiles.active=dev

# Default locale for animal types
app.locale=GR

# File upload configuration
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Custom file upload properties
app.upload-dir=./pet_images
app.pet-id-image-width=200
app.pet-id-image-height=200
app.pet-mh-image-width=1600
app.pet-mh-image-height=1600
